# Generated by Django 5.1.3 on 2025-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_products_price_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
